#!/usr/bin/env python3
from pathlib import Path
from subprocess import run
import pyperclip

from rich import print
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.columns import Columns
from rich.text import Text

def list_commands():
    cmd_list = list(Path('cmddir').iterdir())
    # TODO: check cmddir exists, if not create it

    lst2 = []
    for i in range(0, len(cmd_list)):
        cmd_file = str(cmd_list[i])
        slash_index = cmd_file.find("/")
        dot_index = cmd_file.find(".")

        lst = []
        for j in range(slash_index+1, dot_index):
            lst.append(cmd_file[j])
        
        file_name = "".join(lst)
        lst2.append(file_name)

    lst2 = sorted(lst2) # Sort list alphabetically

    return lst2


def render_main_menu(stored_commands):
    console = Console()

    # View Saved Commands column
    table1 = Table(show_header=False, box=None, pad_edge=False)
    table1.add_column("No.", style="green", width=1, justify="right")
    table1.add_column("Option", style="cyan")

    for i, opt in enumerate(stored_commands, start=1):
        table1.add_row(str(i)+")", opt)

    # Menu Options column
    table2 = Table(show_header=False, box=None, pad_edge=False)
    table2.add_column("Option")
    table2.add_row("[green]a)[/green] add")
    table2.add_row("[green]e)[/green] edit")
    table2.add_row("[green]d)[/green] delete")
    table2.add_row("[green]q)[/green] quit")

    # Panels inside of main box
    columns = Columns(
        [
            Panel(table1, title="View Saved Commands", padding=(1,4)), # Don't set to white bc of light theme
            Panel(table2, title="Menu Options", padding=(1,4)),
        ],
        equal=False,
        expand=True,
    )

    # Main box
    console.print(
        Panel(
            columns,
            title="[bold]CMD-BANK[/bold]",
            border_style="green",
            padding=(0, 1),
        )
    )


def add(stored_commands):
    print("Enter name of command to add:")
    cmd = input("> ")

    if cmd in stored_commands:
        print("This command already exists.")
    else:
        cmd_file = cmd + ".txt"
        path = Path.cwd().joinpath('cmddir', cmd_file)
        open(path, "x")
        print(cmd, "has been added")

    main()
    return


def edit(stored_commands):
    print("Enter name of command to edit:")
    cmd = input("> ")
    if cmd in stored_commands:
        cmd_file = cmd + ".txt"
        path = Path.cwd().joinpath('cmddir', cmd_file)
        run(["nano", path])
    else:
        print("This command does not exist.")

    main()
    return


def delete(stored_commands):
    print("Enter name of command to delete:")
    cmd = input("> ")

    if cmd in stored_commands:
        cmd_file = cmd + ".txt"
        path = Path.cwd().joinpath('cmddir', cmd_file)
        path.unlink()
    else:
        print("This command does not exist.")

    main()
    return


def view(stored_commands, usr_input):
    console = Console()
    text = Text()

    cmd_num = int(usr_input)
    #TODO: entering 0 should be invalid

    selected_cmd = stored_commands[cmd_num-1]

    cmd_file = selected_cmd + ".txt"
    cmd_path = Path.cwd().joinpath('cmddir', cmd_file)

    # Format contents of command file to .READCMD
    cmd_num = 0
    with open(".READCMD", "w") as f1:
        with open(cmd_path, "r") as f2:
            
            for l in f2:

                # If reading the info line
                if l[0] == "#":
                    info = l[1:].strip()
                    text.append("\n"+info, style="italic")

                # If reading the command line
                else:

                    # If line is blank (space between two commands)
                    if l.strip() == "":
                        text.append("\n\n")
                    else:
                        cmd_num += 1
                        number = "["+str(cmd_num)+"]"

                        f1.write("%d\n" % cmd_num)
                        f1.write(l.strip() + "\n")

                        command = l.strip()
                        text.append(number, style="yellow")
                        text.append(" ")
                        text.append(command, style="cyan")
        #TODO: Fix when there are no comments in a command file, still allow for new lines between the commands e.g. in ssh file

        # Back option
        text.append("\n\nb)", style="green")
        text.append(" ")
        text.append("back", style="white")

        console.print(
            Panel(
                text,
                title="[bold]"+selected_cmd+"[/bold]",
                border_style="green",
            )
        )

    cmd_choice = input("\n> ")

    # Return to main menu if back option is selected
    if cmd_choice == "b":
        main()
        return # Kills old view() instance
        
    select = False
    with open(".READCMD", "r") as f1:

        # Iterates through all lines in .READCMD
        for l in f1:
            if select:
                select = False
                saved_cmd = l.strip()

            if l.strip() == cmd_choice:
                select = True
            else:
                pass
                #TODO: Only accept numbers from .READCMD e.g. reject 54637289 or "asdf"

        print("\nCommand has been copied to you clipboard!")
        pyperclip.copy(saved_cmd)


def ui_menu(stored_commands):
    render_main_menu(stored_commands)
    usr_input = input("\n> ")
    print("")

    try:
        view(stored_commands, usr_input)
    except:
        match usr_input:
            case "a":
                add(stored_commands)
            case "e":
                edit(stored_commands)
            case "d":
                delete(stored_commands)
            case "q":
                return
            case _:
                print("Error - Invalid input")
            #TODO: Add settings options for theme etc.


def main():
    stored_commands = list_commands()
    ui_menu(stored_commands)

    cmddir_path = Path('cmddir') / 'nmap.txt'

    file_exists = cmddir_path.is_file()

    if file_exists:
        pass
    else:
        print("File does not exists")
    

if __name__ == "__main__":
    main()